version : "3"

services:
  database:
    image: "postgres"
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
  backend:
    ports: 
      - "8080:8080"
    build: "."
    depends_on: 
      - database
    restart: always
    